BookShop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import TemplateView

from BookShop.aws import conf
from Bookies.models import Book, Review

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'),
         {'books': Book.objects.all(),
          'newest_book': Book.objects.all().order_by('-id')[:4],
          'newest_review': Review.objects.all().order_by('-id')[:4]
          },
         name="index"),
    path('admin/', admin.site.urls, name='admin'),
    path("accounts/", include("accounts.urls")),
    path('bookies/', include('Bookies.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(conf.MEDIA_URL, document_root=conf.MEDIA_ROOT)

Bookies/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from BookShop.aws import conf
from Bookies import views
from Bookies.views import BooksListView, AuthorsTemplateView, \
    CategoryTemplateView, BookDetailView, \
    AuthorDetailView, CategoryDetailView, BookEditView, BookCreateView, \
    BookDeleteView, AuthorCreateView, \
    AuthorEditView, AuthorDeleteView, CategoryCreateView, CategoryEditView, \
    CategoryDeleteView, AddOrderItemView, \
    CartView, Checkout, ReviewCreateView, ReviewEditView, ReviewDeleteView, \
    DeleteOrderItemView

handler404 = 'Bookies.views.handler404'

urlpatterns = [
    path('all/', BooksListView.as_view(), name='allbooks'),
    path('all/<slug:slug>/', BookDetailView.as_view(), name='bookdetails'),
    path('all/create/', BookCreateView.as_view(), name='createbook'),
    path('all/edit/<int:pk>', BookEditView.as_view(), name='editbook'),
    path('all/delete/<int:pk>', BookDeleteView.as_view(), name='deletebook'),

    path('authors/', AuthorsTemplateView.as_view(), name='authors'),
    path('authors/<slug:slug>/', AuthorDetailView.as_view(),
         name='authordetails'),
    path('authors/create/', AuthorCreateView.as_view(), name='createauthor'),
    path('authors/edit/<int:pk>', AuthorEditView.as_view(), name='editauthor'),
    path('authors/delete/<int:pk>', AuthorDeleteView.as_view(),
         name='deleteauthor'),

    path('categories/', CategoryTemplateView.as_view(), name='categories'),
    path('categories/<slug:slug>', CategoryDetailView.as_view(),
         name='categorydetials'),
    path('categories/create/', CategoryCreateView.as_view(),
         name='createcategory'),
    path('categories/edit/<int:pk>', CategoryEditView.as_view(),
         name='editcategory'),
    path('categories/delete/<int:pk>', CategoryDeleteView.as_view(),
         name='deletecategory'),

    path('review/<int:order_item_id>/create/', ReviewCreateView.as_view(),
         name='createreview'),
    path('review/edit/<int:pk>', ReviewEditView.as_view(), name='editreview'),
    path('review/delete/<int:pk>', ReviewDeleteView.as_view(),
         name='deletereview'),

    path('add_item/<int:book_id>/', AddOrderItemView.as_view(),
         name='add_order_view'),
    path('cart/delete/<int:pk>', DeleteOrderItemView.as_view(),
         name='deleteorderitem'),
    path('cart/', CartView.as_view(), name='cart_view'),
    path('checkout/', Checkout.as_view(), name='checkout'),

    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(conf.MEDIA_URL, document_root=conf.MEDIA_ROOT)

Bookies/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg, Sum
from django.utils.text import slugify

from Bookies.constants import OrderStatuses


# book model

class Book(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    description = models.TextField()
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(0.01)])
    available = models.BooleanField()
    img = models.ImageField(blank=True, null=True, upload_to='img', default='book_default.jpg')
    category = models.ManyToManyField("Category")
    order = models.ManyToManyField("Order", blank=True)

    def __str__(self):
        return self.title

    class Meta:
        get_latest_by = 'id'

    @property
    def rating(self):
        return Review.objects.filter(order_item__book_id=self, order_item__order__status=30).aggregate(
            Avg('rating')).get('rating__avg')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)


# Author model
class Author(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    description = models.TextField()
    img = models.ImageField(blank=True, null=True, upload_to='img', default='writer_default.jpg')

    def __str__(self):
        return self.name


# Category model
class Category(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(max_length=255, null=True, unique=True)

    def __str__(self):
        return self.name


# Review model
class Review(models.Model):
    order_item = models.OneToOneField("OrderItem", on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, null=True, unique=True)
    rating = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ])
    comment = models.TextField()

    def __str__(self):
        return str(self.order_item)


# Order / OrderItem models
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    status = models.PositiveSmallIntegerField(choices=OrderStatuses.Choices)
    price = models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=2,
                                validators=[MinValueValidator(0.01)])

    def __str__(self):
        return self.user.username

    @classmethod
    def get_editable_order(cls, user):
        order = cls.objects.filter(user=user, status=OrderStatuses.EDITABLE)
        if order.count() == 0:
            order = cls.objects.create(user=user, status=OrderStatuses.EDITABLE)
        elif order.count() > 1:
            raise Exception(f'This user has more than one editable order. \
                User {user.id}, Order ids {", ".join(str(id) for id in order.values_list("id", flat=True))}')
        else:
            order = order.last()
        return order

    @property
    def get_total_price(self):
        return self.ordered_items.aggregate(total_price=Sum('book__price')).get('total_price', 0)

    def close_order(self):
        self.status = OrderStatuses.COMLETED
        self.total_price = self.get_total_price
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey("Order", related_name='ordered_items', on_delete=models.CASCADE)
    book = models.ForeignKey("Book", related_name='ordered_items', on_delete=models.PROTECT)

    def __str__(self):
        return self.book.title

    class Meta:
        get_latest_by = 'id'

templates/EditUser.html
{% extends "base.html" %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

templates/UserProfile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <main id="main">
    <section id="team" class="team section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>User name: {{ user.username }}</h2>
                <h3>First name: {{ user.first_name }}</h3>
                <h3>Last name: {{ user.last_name }}</h3>
                <p>email: {{ user.email }}</p>
                <h4><a href="{% url "changepassword" %}">Change password</a>

                    <a href="{% url 'userchange' user.id %}">edit profile</a>
                </h4>
            </div>
        </div>
    </section>
    <section id="team" class="team section-bg">
    <div class="container" data-aos="fade-up">

    <div class="section-title">
        <h2>Your books</h2>
    </div>

    <div class="row">
        {% for order_item in order_items %}

            <div class="col-lg-3 col-md-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
                <div class="member">
                    <div class="member-img">
                        <a href="{% url 'bookdetails' order_item.book.pk %}"><img
                                src="{{ order_item.book.img.url }}" class="img-fluid" alt=""></a>
                    </div>
                    <div class="member-info">
                        <h2 class="title"><a
                                href="{% url 'bookdetails' order_item.book.slug %}">{{ order_item.book.title }}</a>
                        </h2>
                        <h4>{{ order_item.book.author }}</h4>
                        <h4><a href="{% url 'createreview' order_item.id %}">Create review</a></h4>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>

{% endblock %}

templates/all_books.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <div class="container" data-aos="fade-up">
        <form method="get" action="" id="searchform">
            <input class="icofont-search-document" id="searchbar" name="q" type="text"
                   value="{{ request.GET.q }}" placeholder="Search...">
            <input type="submit" value="search">
        </form>
    </div>
    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured-services">
        <div class="container" data-aos="fade-up">

            <div class="row">
                {% for book in book_list %}
                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                            <div class="img-fluid"><a href="{% url 'bookdetails' book.slug %}"><img
                                    src="{{ book.img.url }}" width="200"></a></div>
                            <h2 class="title"><a href="{% url 'bookdetails' book.slug %}">{{ book.title }}</a></h2>
                            <h5 class="description">{{ book.author }}</h5>
                            <p class="description">{{ book.description|truncatechars:255 }}</p>
                            <h5 class="description">{{ book.price }}</h5>
                            <form action="{% url 'add_order_view' book.id %}" method="post">{% csrf_token %}<input
                                    type="submit" value="Add"></form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>

        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&q={{ query }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&q={{ query }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&q={{ query }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&q={{ query }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>

    </section>
    {% if user.is_staff %}
        <a href="{% url 'createbook' %}">Add book</a>
    {% endif %}
{% endblock %}

templates/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}


    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock %}

templates/author_details.html
{% extends 'base.html' %}

{% block content %}
<div class="container" data-aos="fade-up">
            <div class="img-fluid"><img src="{{ author.img.url }}" width="200"></div>
            <h2 class="title">{{ author.name }}</h2>
            <h5 class="description">{{ author.description }}</h5>
            <h3> Books:</h3> {% for book in author.book_set.all %}
            <ul>
                <li class=""><a href="{% url 'bookdetails' book.slug %}"> {{ book.title }}</a></li>
            </ul>
        {% endfor %}
    {% if user.is_staff %}
        <div>
            <ul>
                <li><a href="{% url 'editauthor' author.id %}">Edit</a></li>
                <li><a href="{% url 'deleteauthor' author.id %}">Delete</a></li>
            </ul>
        </div>
        </div>
    {% endif %}

{% endblock %}

templates/author_form.html
{% extends "base.html" %}

{% block content %}

    <form action='' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Bookers</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: BizLand - v1.1.0
    * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>


<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="{% url 'index' %}">Bookers<span>.</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt=""></a>-->

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'index' %}">Home</a></li>
                <li><a href="#testimonials">New reviews</a></li>
                <li class="drop-down"><a href="{% url 'allbooks' %}">Catalog</a>
                    <ul>
                        <li><a href="{% url 'allbooks' %}">All</a></li>
                        <li><a href="{% url 'authors' %}">by Authors</a></li>
                        <li><a href="{% url 'categories' %}">by Category</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li><a href="{% url 'cart_view' %}">Cart</a></li>
                {% if user.is_authenticated %}
                    <li class="drop-down"><a href="{% url "userprofile" user.id %}">Hello {{ user.username }}</a>
                        <ul>
                            <li><a href="{% url "userprofile" user.id %}">User profile</a></li>
                            <li><a href="{% url "logout" %}">Log-out</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class='drop-down'><a>Guest</a>
                        <ul>
                            <li><a href="{% url 'login' %}">Log-in</a></li>
                            <li><a href="{% url 'registration' %}">Create account</a></li>

                        </ul>
                    </li>
                {% endif %}
            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
        <h1>Welcome to <span></span>Bookers</spa>
        </h1>
        <h2>We are the coolest book store online!</h2>
        {% if not user.is_authenticated %}
            <div class="d-flex">
                <a href="{% url 'registration' %}" class="btn-get-started scrollto">Get Started</a>
            </div>
        {% endif %}
    </div>
</section><!-- End Hero -->


<section id="my_content">
    {% block content %}
    {% endblock %}
</section>

<!-- ======= Footer ======= -->
<footer id="footer">


    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>Bookers<span>.</span></h3>
                    <p>
                        plac Defilad 1, <br>
                        00-901 Warszawa<br>
                        Poland <br><br>
                        <strong>Phone:</strong> +48 22 666 99 66<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>
                </div>


                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Social Networks</h4>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container py-4">
        <div class="copyright">
            &copy; Copyright <strong><span>Bookies</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/book_details.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <div class="container" data-aos="fade-up">
                <div class="section-title">

     <div><img src="{{ book.img.url }}" width="200"></div>
                 <h2 class="title">{{ book.title }}</h2>
                 <h5 class="description"><a href="{% url 'authordetails' book.author_id %}"> {{ book.author }}</a>
            </h5>
                </div>
                <p class="description">{{ book.description }}</p>
                price <h5 class="description">{{ book.price }}</h5>
                available <h5 class="description">{{ book.available }}</h5>
                categories: {% for category in book.category.get_queryset %}
                <h5 class="description"><a href="{% url 'categorydetials' category.id %}">{{ category.name }} </a></h5>
            {% endfor %}

        <div>
            <p> Average rating: {{ book.rating }}</p>
            <p> Reviews:
                {% for review in reviews %}
                    <ul>
                        <li>User {{ review.order_item.order.user.username }} rating: {{ review.rating }} <br>
                            Review: {{ review.comment }}
                        </li>
                    </ul>
                {% endfor %}

            </p>
            <ul>
                <form action="{% url 'add_order_view' book.id %}" method="post">{% csrf_token %}<input type="submit"
                                                                                                       value="Add to cart">
                </form>
                {% if user.is_staff %}
                    <li><a href="{% url 'editbook' book.id %}">Edit</a></li>
                    <li><a href="{% url 'deletebook' book.id %}">Delete</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/book_form.html
{% extends "base.html" %}

{% block content %}

    <form action='' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

templates/categories.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
        <div class="container" data-aos="fade-up">

        <form method="GET" action="" id="searchform">
            <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}"
                   placeholder="Search..."/>
            <input class="btn-primary" type="submit" value="search">
        </form>
    </div>
    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured">
        <div class="container" data-aos="fade-up">

            <div class="row">
                {% for category in category_list %}
                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
                        <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
                            <h2 class="title"><a href="{% url 'categorydetials' category.slug %}"
                            >{{ category.name }}</a>
                            </h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="pagination">
    <span class="btn-group">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first </a>
            <a href="?page={{ page_obj.previous_page_number }}"> previous   </a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"> next </a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> last &raquo;</a>
        {% endif %}
    </span>
        </div>
        {% if user.is_staff %}
            <a class="" href="{% url 'createcategory' %}">Add category</a>
        {% endif %}
{% endblock %}

templates/category_form.html
{% extends "base.html" %}

{% block content %}

    <form action='' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

templates/change_password.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>

{% endblock %}

templates/orderitem_confirm_delete.html
{% extends "base.html" %}

{% block content %}


    <form method="post">{% csrf_token %}
        <p>Are you sure you want to remove from your cart "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock %}